### ISSUE TITLE
View API support

### ISSUE THREAD

**Issue by AhmedBelal** [cburnette/boxr#10]
Any plans to support Box's View API?

https://box-view.readme.io/reference

**Comment by cburnette** [comment]
actually, it’s just in beta at the moment but we are rolling the view api functionality into the content api.  Meaning that there is now an endpoint in the content api to get a url to preview the document.  It will be generally available in a few months.

Chad

**Comment by AhmedBelal** [comment]
@cburnette Thanks for the heads up. Is the preview functionality of the content API essentially the same as the view API? Is there any reason to prefer one over the other?

**Comment by cburnette** [comment]
It's live now and you can try it from Boxr using embed_url(file).  You get a URL that you can put into an iframe
