### ISSUE TITLE
Box Header Changes - Deadline May 10, 2021

### ISSUE THREAD

**Issue by ascot21** [cburnette/boxr#103]
**Describe the bug**
Box is changing the headers it returns to be case insensitive. This will break this Gem. Deadline is May 10th, 2021.

**The email Box sent out:**

Hello Box Custom App Owner,
 
As previously communicated, we're reaching out to notify you of a change that may affect your Box application(s). If you've already taken corrective actions for your applications based on previous communication, please ignore this message. 
 
On May 10th, 2021, as part of our continued infrastructure upgrade, Box's API response headers will standardize to return in a case insensitive manner, in line with industry best practices and our API documentation. Applications that are using these headers, such as "location" and "retry-after", will need to verify that their applications are checking for these headers in a case-insensitive fashion. Over the past 12 months Box has been upgrading its networking and observability infrastructure. These upgrades aim to improve reliability and availability of Box's products for our customers. This specific change allows Box to deploy an updated service proxy, enabling Box to more easily monitor service traffic, quickly find problem areas, and tune application performance.  

 
How to verify whether your application(s) will be impacted
Verifying whether your application(s) will be impacted will require a review of your code. If you are solely using one of the official Box SDKs to connect to Box APIs, you will not be impacted as the SDKs handle response headers in a case-insensitive manner.
 
You may verify whether you are impacted with the following steps:
Locate the code in your application which handles the responses from Box API requests. If you are not extracting the response headers from these responses, you are not impacted.
If you are extracting those response headers, you may be impacted if you are expecting those headers in a case-sensitive fashion. 
 
For instance, if you are expecting the "Location" header to be returned with a starting capital "L", a direct string comparison with a specific case, then your code will need to be altered to prevent it from breaking after the change is made. 
 
How to make the change
To update the impacted application(s), ensure that you are checking these response headers in a case-insensitive manner. Specifically, your code should be built in a defensive way to ensure that if a header, such as "Location", is sent with an initial capital "L" or a lowercase "l", it'll be handled in the same way. For example, forcing all headers to lowercase before checking, or using a case-insensitive regex string check, are two viable methods for handling this process. 
 
Additional dates to be aware of
In addition to the date that this change will take effect, May 10th, 2021, we will be running two tests to ensure that we can identify and support applications that may be impacted. During these tests, if your application is impacted, you may see an increase in error rates when checking for those headers. The current dates of these tests, which may shift, are:
March 15th, 2021
April 22nd, 2021
 
If you see an increase in failure rates during these periods, your application(s) will be impacted on May 10th, 2021 and will need to be adjusted using the above steps.
 
Where to get support
Should you have any issues or need further guidance, please file a ticket with our support team or post a request to our developer forum for any help needed.
 
We appreciate your partnership as we continue to enhance our services to best meet your business needs.  
 
Thank you,
The Box Developer Team

**Comment by xhocquet** [comment]
Thanks for your report. This issue was investigated and is a non-issue for this library - https://github.com/cburnette/boxr/issues/99
