### ISSUE TITLE
Release a version that does not cause Hashie conflict messages

### ISSUE THREAD

**Issue by shawnacscott** [cburnette/boxr#113]
**Is your feature request related to a problem? Please describe.**
The most recently released version of this gem (1.18.0) produces an error with the pinned `hashie` version, as seen in #41. This has been fixed in #112, but is not yet included in any released version. This has caused a huge amount of log spam that my applications must filter or suppress. 

**Describe the solution you'd like**
A new version release that includes work completed in #112.

**Describe alternatives you've considered**
Currently, my workaround is to pin this gem's version via ref, like `gem 'boxr', github: 'cburnette/boxr', ref: '140f0d'`. However, I would prefer to rely on an official version.

**Additional context**
I would be happy to submit a PR to bump the version to 1.19.0, but did not see any documentation on whether that would meet the requirements for a version release. Please let me know if a PR would be welcome, or if there are other requirements that must be met before `boxr` can have a new version release.

**Comment by xhocquet** [comment]
Thanks for the heads up @shawnacscott! I'll cut a release as soon as I can, sorry for the headache

**Comment by xhocquet** [comment]
@shawnacscott New release 1.19.0 is now available - https://rubygems.org/gems/boxr/versions/1.19.0
