### ISSUE TITLE
*** Boxr::BoxrError Exception: 404: Not Found when create_folder with boxr gem

### ISSUE THREAD

**Issue by trungtran1512** [cburnette/boxr#118]
**Describe the bug**
*** Boxr::BoxrError Exception: 404: Not Found

**To Reproduce**
1. Install gem boxr in project using ruby 3.1.0 and rails 7.0.4
2. get_tokens
`token = Boxr.get_tokens(client_id: client_id, client_secret: client_secret, grant_type: 'client_credentials')`
4. create client:
`client = Boxr::Client.new(token.access_token)`
6. create_folder with client
`client.create_folder(folder_name, parent_folder_id)`
7. raise exp: 
`lib/boxr/client.rb:250:in 'check_response_status': 404: Not Found (Boxr::BoxrError)`

**Expected behavior**
Folder created successfully

**Screenshots**
```
client = Boxr::Client.new(token.access_token)
client.create_folder(folder_name, parent_folder_id)

["/home/name_device/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/boxr-1.19.0/lib/boxr/client.rb:250:in `check_response_status'", 
"/home/name_device/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/boxr-1.19.0/lib/boxr/client.rb:160:in `post'", 
"/home/name_device/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/boxr-1.19.0/lib/boxr/folders.rb:54:in `create_folder'
```

**Desktop:**
 - OS: Linux Ubuntu 22.04.1 LTS
 - Ruby version: 3.1.0
 - Rails version: 7.0.4
 - boxr gem: https://github.com/cburnette/boxr

Please help me if you know the answer to this. Thank you so much!!!

**Comment by xhocquet** [comment]
Hey @trungtran1512 , do you happen to have the full reproducible snippet including the strings/variables you're using in the `create_folder` call?

The test for this feature is passing, so I'm not sure yet what is failing. Based on 404 not found, my gut is that you're passing an invalid `parent_folder_id` that Boxr cannot find during the request.

Let me know if you can provide any more info!

**Comment by trungtran1512** [comment]
@xhocquet 
I didn't use the boxr gem to call the api anymore.
I used the box api to create services through ruby's `net/HTTP` library.
I think the gem is working fine, I guess the problem is that I passed the wrong data so the `create_folder` on the box failed.
If I have time I will use it again. If the feature has passed then I think there will be no problem.

Thank you so much!

**Comment by xhocquet** [comment]
Sounds good!
