### ISSUE TITLE
upgrade from 0.29.0 to 1.0.0 breaking the search functionality

### ISSUE THREAD

**Issue by trustarun** [cburnette/boxr#12]
Below code working fine for me with version 0.29.0

    client = Boxr::Client.new(user.box_access_token)
    box_files = client.search(file_extensions: 'pptx')

It was returning me files for the user, but some how created_at_range  parameter not working for me.

box_files = client.search(file_extensions: 'pptx',created_at_range: "2014-05-15T13:35:01,2015-11-17T13:35:01")

It was always returning same set of files irrespective of what ever created_at_range I set .

So I upgraded the gem to current version, thinking it will solve my problem, But now the search not at all working.

This is the output on my rails console with version 1.0.0

2.2.1 :005 > client = Boxr::Client.new(user.box_access_token, 
                                                           refresh_token: user.box_refresh_token,
                                                           client_id: Rails.application.secrets.box["client_id"],
                                                           client_secret: Rails.application.secrets.box["client_secret"])

** client returned successfully as below

Boxr::Client:0xb46c3ae0 @access_token="0U3TYhMldlgLBWArgDeuzVUeApdY7NRR", @refresh_token="DFo63AY73G8ASSmDgvEeojKK2x2mbGWdkgz2XM8841iBhNGqtJiqDwo1gn3koWR4", @client_id="w5w10iyui36h0wvi5j5e258rk0lqq7uh", @client_secret="c6RTxIqpncT6fZNsMadiziuwTohtKSVh", @enterprise_id=nil, @jwt_private_key=nil, @jwt_private_key_password=nil, @jwt_public_key_id=nil, @identifier=nil, @as_user_id=nil, @token_refresh_listener=nil

2.2.1 :008 >  box_files = client.search(file_extensions: 'pptx')

** searching on client return below error

Boxr::BoxrError: 400: Bad Request
	from /home/arun/.rvm/gems/ruby-2.2.1@respond/gems/boxr-1.0.0/lib/boxr/client.rb:238:in `check_response_status'
	from /home/arun/.rvm/gems/ruby-2.2.1@respond/gems/boxr-1.0.0/lib/boxr/client.rb:103:in `get'
	from /home/arun/.rvm/gems/ruby-2.2.1@respond/gems/boxr-1.0.0/lib/boxr/search.rb:48:in `search'

Can you please help me with what I am doing wrong here.

**Comment by cburnette** [comment]
Yes I'll check into it later today when I'm at my computer. Thanks

**Comment by trustarun** [comment]
Below code worked for 0.29.0

client = Boxr::Client.new(user.box_access_token)
box_files = client.search('pptx', file_extensions: 'pptx', created_at_range: "#{last_synced_date},#{Time.now.to_datetime.rfc3339}")

The problem was that, search call on Box API have query as a required parameter , But I was not passing that. 

Since I want to least all the pptx files rather then file with specific name, I passed 'pptx' as the file name.

As far as 1.0.0 is concerned, you have allowed nil as query value in case user do not pass query parameter, which results in "Boxr::BoxrError: 400: Bad Request"
