### ISSUE TITLE
Bug when an upload session commits and Box returns a 202

### ISSUE THREAD

**Issue by iamricks** [cburnette/boxr#121]
**Describe the bug**
When [chunked_upload_commit_from_io](https://github.com/cburnette/boxr/blob/54aee71025b1a80dc7cc42b5bccca7ae5df6513c/lib/boxr/chunked_uploads.rb#L84) is called, it calls [post](https://github.com/cburnette/boxr/blob/54aee71025b1a80dc7cc42b5bccca7ae5df6513c/lib/boxr/client.rb#L145) in the client.

According to [Box docs](https://developer.box.com/reference/post-files-upload-sessions-id-commit/#response), it is possible to be returned a `202`.

When Box returns a `202`, since post only has `success_codes: [201]` defined, it will end up going into [check_response_status](https://github.com/cburnette/boxr/blob/54aee71025b1a80dc7cc42b5bccca7ae5df6513c/lib/boxr/client.rb#L249) and it will `raise BoxrError`.

**Expected behavior**
`202` is a successful call and should be handled properly instead of raising an error

**Comment by xhocquet** [comment]
Ah, good find @iamricks , and thanks for the thorough documentation you provided.

Would you be interested in opening a PR to add the `202` to the allowed error codes? Should be a pretty easy fix to get merged!

**Comment by iamricks** [comment]
Hey @xhocquet, added the 202 in the list of successful responses in this [PR](https://github.com/cburnette/boxr/pull/122)

**Comment by iamricks** [comment]
@xhocquet Any chance you can help me get this merged?

**Comment by xhocquet** [comment]
@iamricks Sorry for the late reply, it's been a busy couple of months. Please check out the comment I left over on the PR and I'll try to be more responsive to get this merged 🙏🏻

**Comment by monkseal** [comment]
@xhocquet @iamricks Does [this PR](https://github.com/cburnette/boxr/pull/131) resolve this issue?

**Comment by xhocquet** [comment]
Yep looks good @monkseal ! Thanks 🙏🏻

**Comment by xhocquet** [comment]
Pushed a new release to rubygems with this change
