### ISSUE TITLE
Boxr::WebhookValidator fails to validate V2 webhook signatures

### ISSUE THREAD

**Issue by ryankon** [cburnette/boxr#127]
**Describe the bug**
I tried running the latest version of this gem ([v1.20.0](https://github.com/cburnette/boxr/releases/tag/v1.20.0)) with Ruby 3.2.2 and Rails 7.1.2. With V2 webhooks, the validation fails and returns the same signature every time. 

**To Reproduce**
1. Create a Box V2 webhook
2. Perform the appropriate action that triggers the webhook
3. Run `.valid_message?` in the controller
4. Signature validation fails

**Expected behavior**
I expect the signature validation to pass.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I've fixed the issue in my forked repo here: https://github.com/windrushlabs/boxr/commit/cbac55def7d8ba4153fb7804df5ca3ddb7cff33c

However, I do not know the implications of this, specifically with V1 webhooks and older Ruby versions, and the tests failed to run, though I have not yet spent time to figure out why.

**Comment by ryankon** [comment]
@xhocquet I wanted to follow up on this. As far as I can tell, webhook validation is broken completely unless this is merged. I'm running this in production via a fork currently, and everything seems to be working well. Thanks!

**Comment by xhocquet** [comment]
Hey @ryankon, sorry I haven't been able to take a look at this, we don't use Box at my job anymore so any contributions here have been on the side. No promises, but I'll keep this on my radar to see if I can get it merged + released. Thanks for the ping

**Comment by ryankon** [comment]
Hi @xhocquet! Hope you've been well! I wanted to follow up and see if we could get this merged.

I also wanted to volunteer to help with maintaining this repo, given that my firm is using a fork of this in production now, and it would be great to just work off the main repo.

Thanks!

**Comment by xhocquet** [comment]
Hey @ryankon , that actually sounds completely fine to me. I see you're in Ruby land and contributing regularly, so I'm sure folks would appreciate your help! I actually don't own this repo and so cannot add collaborators, but pinging @cburnette ! Could we add Ryan as a maintainer for this repo?

fwiw happy to review code and all that, I just don't have the build setup readily available these days

**Comment by ryankon** [comment]
Hello @xhocquet and @cburnette! Hope you both are well! I wanted to follow up on this request. Thanks!

**Comment by xhocquet** [comment]
Shot Chad an email since the github notifications might not be making it through 🤞🏻
