### ISSUE TITLE
Declaring BOX_CLIENT at the module level breaks compatibility with webmock

### ISSUE THREAD

**Issue by skalb** [cburnette/boxr#18]
Specifically, https://github.com/cburnette/boxr/blob/master/lib/boxr.rb#L57 means that the BOX_CLIENT can't use the webmock proxy.

Could this be moved to Boxr::Client.new?

See: https://github.com/bblimke/webmock/issues/608

**Comment by cburnette** [comment]
The reason that it’s at the module level is that the HTTPClient gem will utilize HTTP persistent connections within a single instance, and they are thread safe.  This means that every API call (at least within 20 seconds of each other) will not have to renegotiate HTTPS encryption resulting in a large performance increase.

Can you explain a bit more about how this is messing up web mock?

thanks,
Chad

**Comment by skalb** [comment]
Webmock overrides the HTTPClient const: https://github.com/bblimke/webmock/blob/master/lib/webmock/http_lib_adapters/httpclient_adapter.rb#L26

I think if Boxr initializes first, it won't use the WebMockHTTPClient.

It's easy enough to work around, but based on the popularity of webmock, I figured other people may run into the same issue.

**Comment by rposborne** [comment]
+1, It might be worth doing this lazily, it's fine to share the client but it needs to boot after the environment, is fully loaded.

**Comment by mykecameron** [comment]
+1

Burnt a few hours on this, I would be inclined to support the suggestion to initialize the HTTPClient instance lazily. Alternatively, drawing attention to this issue in the README with a suggested workaround would be helpful. Maybe something like:

When using HTTP mocking libraries for testing, you may need to set `Boxr::BOX_CLIENT` to a fresh instance of `HTTPClient` in your test setup after loading the HTTP mocking library. For example, when using WebMock with RSpec you might could add the following to your RSpec configuration:

```ruby
RSpec.configure do |config|
  config.before(:suite) do
    Boxr::BOX_CLIENT = HTTPClient.new
  end
```

**Comment by jprince** [comment]
+1 - After a few hours of digging through source code, I discovered that this was the reason why the VCR gem wasn't creating cassettes for my specs. Given the popularity of the VCR gem for testing Ruby API clients, it'd be great to have native compatibility/support.

**Comment by hoffmanc** [comment]
:+1: I also spent quite a bit of time dealing with no cassettes being created, though thankfully wondered onto this page before starting to dig through source code.  @mykecameron has a working solution - perhaps just a README update would suffice?

**Comment by cburnette** [comment]
added README update per suggestion above.  Thanks!
