### ISSUE TITLE
Request requires higher privileges

### ISSUE THREAD

**Issue by ilyakatz** [cburnette/boxr#20]
I can't seem to find the right set of setting to use that makes boxr work properly

When I use it, I get this error

``` ruby
irb(main):130:0*         token = Boxr::get_enterprise_token(private_key: ENV['JWT_PRIVATE_KEY'],
irb(main):131:1*              private_key_password: ENV['JWT_PRIVATE_KEY_PASSWORD'],
irb(main):132:1*              public_key_id: ENV['JWT_PUBLIC_KEY_ID'],
irb(main):133:1*              enterprise_id: ENV['BOX_ENTERPRISE_ID'],
irb(main):134:1*              client_id: ENV['BOX_CLIENT_ID'],
irb(main):135:1*              client_secret: ENV['BOX_CLIENT_SECRET']);
irb(main):136:0*         box_client = Boxr::Client.new(token.access_token);
irb(main):137:0* box_client.folder_items(Boxr::ROOT)
Boxr::BoxrError: 403: Bearer realm="Service", error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token."
```

I tried to configure the applications with the highest permissions that I was able to select

![image](https://cloud.githubusercontent.com/assets/282514/15617998/82ed034e-2400-11e6-9b61-5aa87beabb95.png)

Any suggestions? Thanks!

**Comment by xhocquet** [comment]
Hey @ilyakatz . Hopefully you managed to figure this out since it's been a while. I just went through the process of setting up the account for the smoke tests, so if you still need help feel free to re-open this and let me know. Cheers
