### ISSUE TITLE
file_from_path doesn't return box code/status

### ISSUE THREAD

**Issue by ilyakatz** [cburnette/boxr#25]
It seems that `Client#file_from_path` doesn't return any of the codes/statuses that are return by the API (https://docs.box.com/docs/detailed-error-messages/)
```
begin
  file = box_client.file_from_path(box_path)
rescue Exception => e
  binding.pry
end
[1] pry(main)> e.code
=> nil
[2] pry(main)> e.status
=> nil
```

**Comment by cburnette** [comment]
Try rescuing a BoxrError instead

**Comment by ilyakatz** [comment]
It's the same

```
irb(main):197:0> begin
irb(main):198:1*       file = box_client.file_from_path(box_path)
irb(main):199:1>   rescue Boxr::BoxrError => e
irb(main):200:1>     puts "status: #{e.status}"
irb(main):201:1>     puts "code: #{e.code}"
irb(main):202:1>   end
status: 
code: 
```

I think the exception raised in this file doesn't propagate Box codes

https://github.com/cburnette/boxr/blob/master/lib/boxr/files.rb#L16

**Comment by cburnette** [comment]
ah yes, this is because you are looking for a file by name which the API does not natively support.  This is a helper function that simply gets the list of items in the folders and looks to see if any of the names match.  No error will be thrown by Box.  That why it’s raising it’s own error.

**Comment by ilyakatz** [comment]
Got it. Going to close this then. /cc @jeffcoh23
