### ISSUE TITLE
The request requires higher privileges than provided by the access token.

### ISSUE THREAD

**Issue by carlflor** [cburnette/boxr#26]
I've been trying to create an App User. To do this, I used `Boxr::get_enterprise_token` to create a client.
After creating the client, I tried calling `create_user` but I get this error:

```
Boxr::BoxrError: 403: Bearer realm="Service", error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token."
```

Here's the code I wrote:

```
  def self.get_enterprise_token
    Boxr::get_enterprise_token(
      private_key: private_key,
      public_key_id: PUBLIC_KEY_ID,
      enterprise_id: BOX_ENTERPRISE_ID,
      client_id: BOX_CLIENT_ID,
      client_secret: BOX_CLIENT_SECRET)
  end

  def self.create_user(name, email)
    client = set_enterprise_client
    @app_user = client.create_user(name, login: email)
  end

  private

  def self.private_key
    OpenSSL::PKey::RSA.new(File.read("private_key.pem"), "mypassword")
  end

  def self.set_enterprise_client
    Boxr::Client.new(
      get_enterprise_token.access_token,
      client_id: BOX_CLIENT_ID,
      client_secret: BOX_CLIENT_SECRET,
      enterprise_id: BOX_ENTERPRISE_ID,
      jwt_private_key: private_key,
      jwt_public_key_id: PUBLIC_KEY_ID)

  end
```

**Comment by jprince** [comment]
Double check the scopes of your application and ensure that it's authorized to manage users:
![image](https://cloud.githubusercontent.com/assets/3384090/19895966/c33409e2-a020-11e6-8237-292bac9db4e3.png)

(screenshot just for reference on where to find the scopes - your application likely requires different permissions)

In my case, the application needed to be re-authorized by the Enterprise admin after I elevated the scopes.

**Comment by xhocquet** [comment]
Hey there. Hopefully this issue was resolved. Feel free to reach back out if there's any questions.
