### ISSUE TITLE
Does Box pdf file support to open in browser instead of force download?

### ISSUE THREAD

**Issue by sushilprj** [cburnette/boxr#27]
I have to implement a capability where the pdf file should default open in the browser when a user tries to download a pdf file.

This gem provide a method download_url which returns a URL  and  when User clicks on the return URL, it forces the browser to download file instead of open in the browser.

**Comment by xhocquet** [comment]
@sushilprj Box does not provide direct links to embed documents/images. You can either download the file or use their Preview API to display the documents within your website using their container: https://developer.box.com/v2.0/docs/file-preview-api

**Comment by xhocquet** [comment]
Closing as I believe this is not functionality Box offers.
