### ISSUE TITLE
Search Created_at_range_from_date

### ISSUE THREAD

**Issue by jindhaliwal** [cburnette/boxr#28]
client.search('2015', scope: nil, file_extensions: [], created_at_range_from_date: Date.parse('2015/01/01').rfc3339)

ArgumentError: unknown keyword: created_at_range_from_date

**Comment by xhocquet** [comment]
Hey @jindhaliwal 

Not sure if this is still an issue for you, but I was just trying it out. In your case, remove `. rfc3339` from your date as the library takes care of the conversion. I tried the command successfully myself:

```
[2] pry(#<RSpec::ExampleGroups::BoxrClient>)> BOX_CLIENT.search('2015', scope: nil, file_extensions: [], created_at_range_from_date: Date.parse('2015/01/01'))
=> []
```

Cheers!
