### ISSUE TITLE
Fixnum deprecation warning on Ruby 2.4.0

### ISSUE THREAD

**Issue by bousquet** [cburnette/boxr#33]
`.../gems/boxr-1.2.0/lib/boxr/client.rb:274: warning: constant ::Fixnum is deprecated`

**Comment by Band-Aid** [comment]
https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/
Unify Fixnum and Bignum into Integer
Though ISO/IEC 30170:2012 doesn’t specify details of the Integer class, Ruby had two visible Integer classes: Fixnum and Bignum. Ruby 2.4 unifies them into Integer. All C extensions which touch the Fixnum or Bignum class need to be fixed.

**Comment by xhocquet** [comment]
Howdy, looks like this was resolved here: https://github.com/xhocquet/boxr/commit/5e68c8c3640f33d709d4830ce34631864b1f5db5

Just tested myself and no warnings! Cheers
