### ISSUE TITLE
400: {"error":"invalid_grant","error_description":"Please check the 'sub' claim."}

### ISSUE THREAD

**Issue by carlflor** [cburnette/boxr#35]
I'm setting up my web app on aws but then I get this error getting an enterprise token.
It works on my local machine. I've already included the private keys for my local machine and server. 

Almost all environment variables are the same, except for the private key path and public key.
Enterprise ID is the same for both.

**Comment by jamesmarrs** [comment]
Hey @carlflor 

Do you have your enterprise key in some type of ENV file? I noticed that the API documentation for the sub attr of the JWT claim needs to be a string, if you dont wrap it in quotes and copied it right from the box admin it wont work!

**Comment by troycarlson** [comment]
Thanks @jamesmarrs, that led me to find a solution.  In my case, I had to make sure my user ID was a string:

`Boxr.get_user_token(123456, ...)`

became

`Boxr.get_user_token("123456", ...)`

**Comment by xhocquet** [comment]
This issue usually stems from misconfigurations or things being passed in unexpectedly. There could be a few reasons, as noted above. Closing since there is no specific thing to fix.
