### ISSUE TITLE
collaboration.rb only allows to collaborate with folders

### ISSUE THREAD

**Issue by Band-Aid** [cburnette/boxr#44]
https://developer.box.com/v2.0/reference#add-a-collaboration

**Comment by xhocquet** [comment]
Hey @Band-Aid , I see you've been active on here every so often, thanks! Could you please add some more detail to this? Which functions are missing from the library? Cheers.

**Comment by Band-Aid** [comment]
@xhocquet great to see we have a new maintainer!

The add_collaboration method has `type: :folder` as a fixed param. 
Collaborations allow `file` or `folder` as type. 
https://github.com/cburnette/boxr/blob/768139802fc5bb6ce22014da6636b24ca5c7eb9e/lib/boxr/collaborations.rb#L18

We should probable allow passing in an item_type to the method.
https://box.dev/en/reference/collaborations/#post-collaborations

Something like this, what do you think?

```
 def add_collaboration(item_type, item, accessible_by, role, fields: [], notify: nil)
      item_id = ensure_id(item)
...
      attributes = {item: {id:item_id, type: :item_type}}
```

**Comment by xhocquet** [comment]
@Band-Aid Excited to get this project some movement!

I think your suggestion makes a ton of sense, collaborations aren't necessarily limited to just one type of item! I agree this should get added. Would you be interested in opening a PR? Some notes for you or whomever takes this on:


   1. Add a new parameters after `role` (`item_type`) with default `:folder` (this preserves backwards compatibility)
   2. Update the first parameter to `item` as you described
   3. Add a test
   4. Update README 

Cheers!

**Comment by xhocquet** [comment]
Closing in favor of https://github.com/cburnette/boxr/pull/91
