### ISSUE TITLE
how to use it with paperclip

### ISSUE THREAD

**Issue by uzaif313** [cburnette/boxr#56]
how to configure `boxr` with paperclip and use it with existing model of rails

**Comment by xhocquet** [comment]
Hi @uzaif313 . While I cannot provide a full example, based on my understanding of Paperclip you would need to write a Box adapter for it to be able to upload/download content from Box as necessary.

I would recommend looking at their dropbox adapter which may give you hints on how to do this: https://github.com/janko/paperclip-dropbox

That being said, Paperclip has been deprecated and so I would not recommend investing heavily into it if you can avoid it! Cheers.
