### ISSUE TITLE
Users as User link doesn't work

### ISSUE THREAD

**Issue by skplunkerin** [cburnette/boxr#59]
Please update your README with correct url for User as User.

This url is outdated and takes you to the Docs main "Overview" page.

- https://developers.box.com/docs/#users-as-user

**Comment by xhocquet** [comment]
Hey @skplunkerin , thanks for the heads up. I've updated the link with the proper reference: https://github.com/cburnette/boxr/commit/768139802fc5bb6ce22014da6636b24ca5c7eb9e
