### ISSUE TITLE
nextStreamPosition value is malformed

### ISSUE THREAD

**Issue by jonathansimmons** [cburnette/boxr#60]
So I wrote an app a while ago to poll events and we noticed this week it had stop working. In reviewing the implementation, I found that it's essentially identical to the [enterprise_events](https://github.com/cburnette/boxr/blob/master/examples/enterprise_events.rb) example. 

The problem I'm seeing is that the actual `client.enterprise_events_stream` is returning a error of `400: nextStreamPosition value is malformed`.

Any direction on what might this be causing?

**Comment by jonathansimmons** [comment]
@cburnette Any thoughts here? is there another support channel I should be using?

**Comment by xhocquet** [comment]
Hey @jonathansimmons , sorry for the late response. Is this still an issue? Do you have any other details to provide? I imagine testing this may be hard since it would require generating some amount of events.

**Comment by jonathansimmons** [comment]
As far as I know yes, I no longer work for the company I was writing the custom integration for. We just abandon the reporting tool because no one was responding here and internal Box Support didn't understand. 

As for testing, I don't think it would be hard. I was using a slightly modified version of the [enterprise events example](https://github.com/cburnette/boxr/blob/master/examples/enterprise_events.rb)

So I imagine if you run that against an account you'd see the same `400: nextStreamPosition value is malformed`. Unless it was something wrong with the account data coming back from my previous employer's Box account.

**Comment by xhocquet** [comment]
@jonathansimmons Thanks for the context! I'll keep an eye out for this issue since I don't see it being reported elsewhere yet. When I have some time I'll look into testing out the example in the repo.

**Comment by jonathansimmons** [comment]
Cool, I’m willing to help if it comes back around, though I don’t have a box enterprise account to test with anymore. (Realizing that might have been your point at first). In the meantime can you please remove my assignment on this issue?

**Comment by xhocquet** [comment]
Going to close this out for now. The initial report cannot be easily recreated, and based on the description I would be surprised if there's a real issue. It was working previously for some time, and then the same method (which is just a constant API call) returned an invalid value that broke the code. Seems that a long-running process would be susceptible to a bunch of problems like network reliability, so this isn't too surprising. Happy to investigate when another report comes in
