### ISSUE TITLE
folder_from_path does not make case insensitive check

### ISSUE THREAD

**Issue by skalb** [cburnette/boxr#61]
See https://github.com/cburnette/boxr/blob/5e68c8c3640f33d709d4830ce34631864b1f5db5/lib/boxr/folders.rb#L13

Folder/file names are case-insensitive in box.

**Comment by xhocquet** [comment]
Hey @skalb , sorry for the pings on the old PR. I was finally reviewing this in depth and agree with your decision. These methods are helper methods provided by the library, and the API itself does not allow users to interact with files/folders by name. Therefore it's up to the library, and this is a much more pleasant experience considering folders/files are unique by case-insensitive name.

New PR here: https://github.com/cburnette/boxr/pull/92

Thanks for the contribution!
