### ISSUE TITLE
create_user check_response_status': 400: Bad Request (Boxr::BoxrError)

### ISSUE THREAD

**Issue by Shannon-PA** [cburnette/boxr#65]
```ruby
tokens = Boxr::get_enterprise_token(private_key: config['appAuth']['privateKey'])

client = Boxr::Client.new(tokens.access_token)

client.create_user("BoxUserAPI")
```

So that's my code. Creating the client succeeds. I can scan files and folders, stuff like that, but creating a user causes this error: `check_response_status': 400: Bad Request (Boxr::BoxrError)`

**Comment by Band-Aid** [comment]
I believe you are trying to create an app user. If that is the case you need to pass in  is_platform_access_only: true
client.create_user("BoxUserAPI",is_platform_access_only: true)

**Comment by Shannon-PA** [comment]
That did it, thanks!
