### ISSUE TITLE
Cannot create shared_link with no expiration

### ISSUE THREAD

**Issue by Shannon-PA** [cburnette/boxr#68]
When creating a shared link, I would like to be able to create a link with no expiration. This requires me to set the 'unshared_at' value that gets sent to box, to 'null'

Passing no value or a 'nil' value simply doesn't set the value to anything, which appears to then create a default 'unshared_at' date about 3 months in the future.

**Comment by xhocquet** [comment]
Hey @Shannon-PA . Looking through the code, I don't see anywhere where the library is setting a default value to 3 months ahead. In fact, it seems where we apply the `unshared_at` value, we only add it in if the value is supplied.

Maybe your Box account is configured in such a way that this is automatic? Or could you recreate the issue in a narrow example? Cheers!

**Comment by xhocquet** [comment]
Closing for now since there's no response. Feel free to re-open if you still need help!
