### ISSUE TITLE
Guide to transition from RubyBox to Boxr

### ISSUE THREAD

**Issue by jbwyatt4** [cburnette/boxr#7]
Hello,

I'm having problems understanding how to use this new SDK. Are their any example Rails applications on how to get started?

I previously came across this app:
https://github.com/atharvasystem/cloud-storage-app/blob/f719189f18370feaee0bfb3fafd02fa37b32b394/app/controllers/linked_accounts_controller.rb

Which showed me how to setup the redirect url, fetch an authorization token, and catch those errors with the old sdk.

**Comment by rposborne** [comment]
+1

**Comment by xhocquet** [comment]
Hey @rposborne @jbwyatt4 . I'm a new maintainer and just going through doing some housekeeping.

The examples in the README are as much as we have available, though at this point I imagine there's apps out there with examples of how this library is used. If you would like to make a simple example app, I would be more than happy to link to that project within the README. Cheers!
