### ISSUE TITLE
400 invalid_grant, Refresh token has expired

### ISSUE THREAD

**Issue by morshedalam** [cburnette/boxr#73]
Using `Standard OAuth 2.0 (User Authentication) ` to create box folder from one of my client app. Recently, we have implemented box webhook callback to upload file from box to AWS. 

Currently, required to update the token manually in every hour as any of the ways mentioned below are not working now but way 2 were working before after implementing webhook I think.

- Token refresh callback as suggested in readme

- Called a method in every initialisation which perform following
>
     unless (Time.now.to_i >= Setting.box_token_expires_in.to_i - 300)
        token                        = Boxr::refresh_tokens(Setting.box_refresh_token, client_id: Setting.box_client_id, client_secret: Setting.box_client_secret)
        Setting.box_access_token     = token.access_token
        Setting.box_refresh_token    = token.refresh_token
        Setting.box_token_expires_in = Time.now.to_i + token.expires_in.to_i
    end

- Used scheduler which execute above code snippet

Can anyone have any suggestion/solution in this regards?

**Comment by xhocquet** [comment]
Hi @morshedalam . The way you are handling this is the expected way to do this for now. This is standard OAuth2 behavior: Refresh tokens work in a 'session' and sometimes expire. When you know this, all you need to do is ask for another one. It is a bit cumbersome in practice with web apps. Cheers!

**Comment by morshedalam** [comment]
Hi @xhocquet, 
Thank you for your reply. Yes, I am using one box account controlling all actions. I will try JSON web token.

Do you think any issue with using same token for creating box folder from my app and also using webhook to upload file from box to AWS. I went through a post about the limit of webhook that is 1000?

**Comment by xhocquet** [comment]
@morshedalam There would not be an issue re-using tokens as long as all permissions exist. You may be concerned about rate-limiting and tokens expiring, and these are common issues with Box as well as other API vendors. See their documentation for notes about rate-limiting: https://developer.box.com/reference#rate-limiting

I've also seen that Box is not so transparent about rate-limits, so you should ask support directly to be sure and not rely only on the documentation. Some additional info can be found in [this post](https://community.box.com/t5/Platform-and-Development-Forum/Understanding-API-Rate-Limits/td-p/32747) where a developer details a mechanism to work around tokens expiring with multiple users. Cheers
