### ISSUE TITLE
Add ability to move content from one folder to another

### ISSUE THREAD

**Issue by clader** [cburnette/boxr#9]
Is there an implementation of the /users/{USER_ID}/folders/{FOLDER_ID} functionality to move items in a users folder to another user?
https://box-content.readme.io/reference#move-folder-into-another-users-folder

Looking at your documentation there are a few move functions, but it's not clear if those are just to move files/folders within the current users file structure.  If the above function is implemented, can you confirm whether the "as_user:" functionality needs to be enabled on our API key to do this?

Thx
~Calder

**Comment by cburnette** [comment]
Good question. I'll check this out tomorrow. 

Chad

**Comment by cburnette** [comment]
No, that is not currently in Boxr (I missed it somehow) but I can add that later today.  It doesn’t look like you need as-user privilege but whatever user you are using to make the call needs to have administrative privileges (though I’m not clear exactly which ones).  I’ll push the code and then try and add a test for it.  If you could try it out and let me know what you find that would help.

thanks,
Chad

**Comment by nayakk** [comment]
Hi Chad, Clader, 

I have submitted a Pull request to fix the issue.

Regards,
Nayak

**Comment by xhocquet** [comment]
Added with https://github.com/cburnette/boxr/pull/75
